### ISSUE TITLE
SFU Mountain Datasets not available

### ISSUE THREAD

**Issue by Enrico-Chiavassa** [QVPR/VPRSNN#17]
Hello @Somayeh-h, thank you for your work!
I am interested in the application of VPR techniques in mountain-like environments, and i would like to run some tests on the SFU mountain dataset. Unfortunately, the links provided in the [official page](https://autonomy.cs.sfu.ca/sfu-mountain-dataset/) appear to all be broken and I could not find any other source for this dataset. Would it be possible for you to make it available while the site is not working? 

Cheers,
Enrico

**Comment by Tobias-Fischer** [comment]
Hi Enrico, please get in touch with the SFU mountain authors to obtain a copy, or permission for us to redistribute.

Thanks, Tobi
