### ISSUE TITLE
About the visualizations of the paper

### ISSUE THREAD

**Issue by MAX-OTW** [QVPR/VPRSNN#2]
Hello, @Somayeh-h ,-I really appreciate for your work！Congratulations :)
The visualizations(**Fig. 3** and **Fig. 4**)in the Non-modular SNN paper and (**Fig. 2** and **Fig. 6**) in the Modular SNN paper look great.Currently I want to try to implement them but I failed. Is it convenient to provide the relevant implementation code?Of course, detailed guidance would be better.
I am always looking forward to your kind response.
Best regards.

**Comment by Somayeh-h** [comment]
Hello @MAX-OTW, thanks for your interest in our work! We have already provided the code to plot these figures. Please refer to `modular_snn_evaluation.py` file for the non-modular SNN paper and `modular_snn_config_evaluation.py` file for the modular SNN paper to see examples of how to plot these figures. I hope you find them useful.   
Thanks,
Somayeh
