### ISSUE TITLE
Could you share the learned weights for the Oxford RobotCar data?

### ISSUE THREAD

**Issue by berthaSZ** [QVPR/VPRSNN#24]
Hello @Somayeh-h,

Could you please share the learned weights for the Oxford RobotCar dataset? I checked #4, #10, and #16. However, I could not find either the data you used or the corresponding learned weights. Therefore, I thought this would require posting a new issue.

I processed my own subset of Oxford data by following the preprocessing instructions in your paper. However, I am getting very low precision at 100% recall values.

Best,
Bertha

**Comment by Somayeh-h** [comment]
Hi @berthaSZ,  

Thanks for reaching out about this! Again, apologies for the delayed reply.  

As you raised a similar issue in the VPRTempo repo [https://github.com/QVPR/VPRTempo/issues/15], Adam has computed the corresponding image names in the original Oxford RobotCar dataset. I have also added the .csv files for the images I used in this repo in the `./dataset_imagenames` folder. Please try again training the model, and reach out if any issues.  

Best, 
Somayeh
