### ISSUE TITLE
Could you release the trained models?

### ISSUE THREAD

**Issue by YuhangMing** [QVPR/VPRSNN#4]
Hi @Somayeh-h, 

We are really interested in this work and would like to play with it. We would like to know if releasing some trained models is possible. Thanks!

Best,
Yuhang

**Comment by Somayeh-h** [comment]
Hi @YuhangMing, 

Thank you for your interest in our work. Yes, we've now made the learned weights of our Modular SNN available. Please see the link below to find the learned weights of our Modular SNN from the Nordland dataset, trained on Spring and Fall traverses (Reference dataset), and calibrated on Summer traverse. The learned weights include the outputs of train, record and calibration processes that is needed for the neuronal assignments, hyperactive neuron detection, and hyperparameter calibration processes. Please see [modular_snn/modular_snn_processing.py](https://github.com/QVPR/VPRSNN/blob/main/modular_snn/modular_snn_processing.py) and [modular_snn/modular_snn_evaluation.py](https://github.com/QVPR/VPRSNN/blob/main/modular_snn/modular_snn_evaluation.py) files for config information. 

Nordland dataset: https://cloudstor.aarnet.edu.au/plus/s/2LtwUtLUFpUiUC8 
Modular SNN learned weights: https://drive.google.com/drive/u/1/folders/1Qwp3h6D1s2CMLXisAUDVGN1Z9EOAQbwA 

Please let me know if you encounter any access issues with the links provided above. 

Best,
Somayeh
