### ISSUE TITLE
Confused aboud the Nordland dataset in the repo and the paper?

### ISSUE THREAD

**Issue by YuhangMing** [QVPR/VPRSNN#6]
Hi @Somayeh-h,

Thank you for your interesting work. But I am really confused about the link you provided to the Nordland dataset [here](https://github.com/QVPR/VPRSNN/blob/modularSNN/non_modular_snn/README.md#run). 

Following the link, the Nordland dataset is already split to train and test, for training, 3 sections per season, and for test, 2 sections per season. However, while reading your paper and looking into your code, you seem to use the entire spring and fall sequence to train the model and use the entire summer sequence for testing, and no sections are used. Also, the file you provided [here](https://github.com/QVPR/VPRSNN/blob/modularSNN/dataset_imagenames/nordland_imageNames.txt) doesn't really match the data format in the dataset link you provided. 

Could you please take a look at this inconsistency?

Best,
Yuhang

**Comment by Tobias-Fischer** [comment]
Hi @YuhangMing, indeed, this is a mistake on our side. We do not use the partitioned Nordland dataset; instead we use a variation of the Nordland dataset as provided here: https://github.com/QVPR/Patch-NetVLAD/issues/57
@Somayeh-h: Could you please change the readme, and provide details how you sub sampled the dataset?

Best, Tobi

**Comment by Somayeh-h** [comment]
Hi @YuhangMing,

Apologies for my lack of explanation, and providing a link to a different variant of the Nordland dataset. I have updated the [README](https://github.com/QVPR/VPRSNN/blob/main/modular_snn/README.md) file to include information about the Nordland dataset. 

We used the entire spring and fall sequences for training, the entire summer sequence for calibration (only the first 600 images after sampling), and testing (the remaining 80%). The number of images in the filtered image list provided [here](https://github.com/QVPR/VPRSNN/blob/modularSNN/dataset_imagenames/nordland_imageNames.txt) should match the number of images in this variation of the Nordland dataset, which is available in the link @Tobias-Fischer provided above. Nordland dataset link: https://cloudstor.aarnet.edu.au/plus/s/2LtwUtLUFpUiUC8

Thanks,
Somayeh

**Comment by Somayeh-h** [comment]
Hi @YuhangMing, 

Please note that each entire traverse is first filtered using the filtered image list mentioned above. Then, the images are sampled by selecting every 8th image. I have just updated the README.md again to make the instructions more clear. 

The scripts [`modular_snn/modular_snn_processing.py`](https://github.com/QVPR/VPRSNN/blob/main/modular_snn/modular_snn_processing.py) and [`modular_snn/modular_snn_evaluation.py`](https://github.com/QVPR/VPRSNN/blob/main/modular_snn/modular_snn_evaluation.py) provide the configurations to run our Modular SNN on the Nordland dataset which also includes the data processing steps detailed above.

Please let me know if there are any issues with running our model on Nordland dataset. 

Thanks,
Somayeh
